steps:
  - id: "Build GPU Docker Image"
    name: "gcr.io/cloud-builders/docker"
    args:
      - "build"
      - "-t"
      - "us-central1-docker.pkg.dev/cer-ufba/petrobras-repo/petrobras-anomaly-detection-gpu:latest"
      - "-f"
      - ".docker/Dockerfile.gpu"
      - "."
    env:
      - "DOCKER_BUILDKIT=1"
  - id: "Push GPU Docker Image"
    name: "gcr.io/cloud-builders/docker"
    args:
      - "push"
      - "us-central1-docker.pkg.dev/cer-ufba/petrobras-repo/petrobras-anomaly-detection-gpu:latest"

options:
  machineType: "E2_HIGHCPU_8"
  diskSizeGb: 100

images:
  - "us-central1-docker.pkg.dev/cer-ufba/petrobras-repo/petrobras-anomaly-detection-gpu:latest"
