services:
  app:
    build:
      context: .
      dockerfile: .docker/Dockerfile.gpu
    ports:
      - "8080:8080"
    environment:
      - PORT=8080
      - PYTHONPATH=/app/src
      - CUDA_VISIBLE_DEVICES=0
      - NVIDIA_VISIBLE_DEVICES=all
      - NVIDIA_DRIVER_CAPABILITIES=compute,utility
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
        limits:
          memory: 8G
          cpus: "4.0"
