[project]
name = "jupyter"
version = "0.1.0"
description = "Jupyter Notebook Template"
readme = "README.md"
requires-python = "==3.11.13"
dependencies = [
    "google-genai>=1.31.0",
    "google-generativeai>=0.8.5",
    "marimo>=0.15.0",
    "pandas>=2.3.2",
    "pip>=25.2",
    "polars>=1.32.3",
    "scikit-learn>=1.7.1",
    "torch>=2.0.1",
    "torchaudio>=2.0.2",
    "torchvision>=0.15.2",
    # Google Cloud AI Platform
    "google-cloud-aiplatform>=1.38.0",
    "google-cloud-storage>=2.10.0",
    "google-cloud-logging>=3.8.0",
    "google-cloud-monitoring>=2.16.0",
    "google-auth>=2.40.3",
    "google-api-python-client>=2.179.0",
    # ML e treinamento distribuído
    "tensorboard>=2.15.0",
    "mlflow>=2.8.0",
    "optuna>=3.4.0",
    "wandb>=0.16.0",
    # Utilitários para cloud
    "python-dotenv>=1.0.0",
    "pyyaml>=6.0.1",
    "click>=8.1.7",
]

[dependency-groups]
dev = [
    "ipykernel>=6.30.1",
    "ipywidgets>=8.1.7",
    "pre-commit>=4.3.0",
    "ruff>=0.12.10",
    "uv>=0.8.13",
    # Ferramentas de desenvolvimento para cloud
    # google-cloud-cli e gcloud são instalados via sistema
]

[[tool.uv.index]]
url = "https://download.pytorch.org/whl/cu117"
