[project]
name = "jupyter"
version = "0.1.0"
description = "Jupyter Notebook Template"
readme = "README.md"
requires-python = ">=3.13"
dependencies = []

[dependency-groups]
dev = [
    "ipykernel>=6.30.1",
    "ruff>=0.12.9",
    "uv>=0.8.11",
]
