[project]
name = "jupyter-security-update"
version = "0.1.0"
description = "Temporary configuration for security updates"
requires-python = "==3.11.13"

# Dependências com versões seguras mínimas
dependencies = [
    # Dependências principais do projeto
    "jupyter>=1.0.0",
    "pandas>=2.3.2",
    "polars>=1.32.3",
    "scikit-learn>=1.7.1",
    "torch>=2.0.1",
    "torchaudio>=2.0.2",
    "torchvision>=0.15.2",

    # ML e treinamento
    "tensorboard>=2.15.0",
    "mlflow>=2.8.0",
    "optuna>=3.4.0",
    "wandb>=0.16.0",

    # Utilitários básicos
    "python-dotenv>=1.0.0",
    "pyyaml>=6.0.1",
    "click>=8.1.7",

    # Dependências para dados
    "pyarrow>=19.0",
    "h5py>=3.13",
    "tslearn>=0.6",
    "ydata-profiling>=4.15",
    "numba>=0.61",
    "missingno>=0.5",
    "alive-progress>=3.2",
    "natsort>=8.4",
    "plotly>=6.0",
    "pydantic>=2.10",
]
