[project]
name = "jupyter"
version = "0.1.0"
description = "Jupyter Notebook Template"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "pandas>=2.3.2",
    "scikit-learn>=1.7.1",
]

[dependency-groups]
dev = [
    "ipykernel>=6.30.1",
    "ipywidgets>=8.1.7",
    "pre-commit>=4.3.0",
    "ruff>=0.12.10",
    "uv>=0.8.13",
]
