services:
  app:
    build:
      context: ..
      dockerfile: .docker/Dockerfile.gcloud
    ports:
      - "8000:8000"
    environment:
      - PORT=8000
      - PYTHONPATH=/home/vscode/app/src
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
