services:
  app:
    image: petrobras-anomaly-detection-dev:latest
    build:
      context: ..
      dockerfile: .docker/Dockerfile
    container_name: petrobras-anomaly-detection
    command: ./.docker/start-app.sh
    volumes:
      # Mount application code
      - ..:/home/vscode/app:delegated
      # Mount zsh configuration files for persistence
      - ../.docker/zsh/powerlevel10k/.p10k.zsh:/home/vscode/.p10k.zsh:delegated
      - ../.docker/zsh/history:/home/vscode/zsh:delegated
      # Mount additional zsh configs
      - ../.docker/zsh/.zshrc:/home/vscode/.zshrc:delegated
      - ../.docker/zsh/.zsh_history:/home/vscode/.zsh_history:delegated
    ports:
      - "8000:8000"
      - "8888:8888" # Jupyter
      - "5000:5000" # MLflow
    environment:
      - TERM=xterm-256color
      - SHELL=/bin/zsh
      - PYTHONPATH=/home/vscode/app/src
      - GEMINI_API_KEY=AIzaSyBaFyO_LDBCkDokJq-wwwBZAcrkC8BVMqo
      - GEMINI_MODEL=gemini-2.0-flash-exp
      - GEMINI_DEBUG=false
      - GEMINI_TELEMETRY=false
      - JUPYTER_ENABLE_LAB=yes
      - MLFLOW_TRACKING_URI=http://localhost:5000
    stdin_open: true
    tty: true
    networks:
      - petrobras-network

networks:
  petrobras-network:
    driver: bridge
