name: Publish Python package

on:
  release:
    types: [created]

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      id-token: write  # Obrigatório para trusted publishing PyPI
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"
      - name: Install build
        run: python -m pip install --upgrade build
      - name: Build package
        run: python -m build
      - name: Publish package to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1
        # Por padrão publica para PyPI; para TestPyPI adicionar:
        # with:
        #   repository-url: https://test.pypi.org/legacy/

  uv-example:
    name: UV Example
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install uv
        uses: astral-sh/setup-uv@v6
      - name: Run uv
        run: uv sync
